#!/bin/sh

CSV=$1
DB=$2

SQLITE=`which sqlite3`

if [ "${CSV}" = "" ]
then
    echo "usage: wof-concordances-to-db /path/to/CSV_FILE /path/to/SQLITE_DB"
    exit 1
fi

if [ "${DB}" = "" ]
then
    echo "usage: wof-concordances-to-db /path/to/CSV_FILE /path/to/SQLITE_DB"
    exit 1
fi

if [ ! -f ${CSV} ]
then
    echo "usage: wof-concordances-to-db /path/to/CSV_FILE /path/to/SQLITE_DB"
    exit 1
fi

if [ ! -x ${SQLITE} ]
then
    echo "it does not appeear that you have sqlite3 installed"
    exit 1
fi

PID=$$
FNAME=`basename ${DB}`
FNAME="${FNAME}-${PID}.sql"
SQL="/tmp/${FNAME}"

if [ -f ${DB} ]
then
    mv ${DB} ${DB}.bak
fi

if [ -f ${SQL} ]
then
    rm ${SQL}
fi

touch ${SQL}

echo "CREATE TABLE concordances(id INTEGER, woe_id INTEGER, geonames_id INTEGER, quattroshapes_id INTEGER,iso,placetype);" >> ${SQL}
echo "CREATE INDEX by_id ON concordances(id);" >> ${SQL}
echo "CREATE INDEX by_woe_id ON concordances(woe_id);" >> ${SQL}
echo "CREATE INDEX by_gn_id ON concordances(geonames_id);" >> ${SQL}
echo "CREATE INDEX by_iso ON concordances(iso);" >> ${SQL}
echo "CREATE INDEX by_placetype ON concordances(placetype);" >> ${SQL}
echo ".mode csv" >> ${SQL}
echo ".import ${CSV} concordances" >> ${SQL}

sqlite3 ${DB} < ${SQL}
rm ${SQL}

exit 0
