#!/usr/bin/env python
# -*-python-*-

import sys
import os
import logging

import mapzen.whosonfirst.utils

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-m', '--meta', dest='meta', action='store', default=None, help='Where your meta files are stored (like the parent directory)')
    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    meta = options.meta

    if not meta:
        logging.error("you forgot to specify a meta file")
        sys.exit()

    if not os.path.exists(meta):
        logging.error("meta file (%s) does not exist" % meta)
        sys.exit()

    mapzen.whosonfirst.utils.update_placetype_metafiles(meta, args)
    sys.exit()
