#!/usr/bin/env python

import sys
import os
import requests
import csv

import mapzen.whosonfirst.utils

if __name__ == '__main__':

    writer = csv.writer(sys.stdout, delimiter='\t')

    for id in sys.argv[1:]:

        relpath = mapzen.whosonfirst.utils.id2relpath(id)

        endpoints = (
            "http://whosonfirst.mapzen.com.s3.amazonaws.com/data/",
            "http://whosonfirst.mapzen.com/data/"
        )

        for root in endpoints:

            url = root + relpath

            rsp = requests.head(url)
            headers = rsp.headers

            etag = headers.get('ETag')
            etag = etag.replace('"', "")

            out = (id, etag, url)
            writer.writerow(out)
